# Site settings
title: "Commonplace Design"
tagline: "A scrapbook of web design patterns"
email: "pam@pamgriffith.net"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://commonplacedesign.com" # the base hostname & protocol for your site

gems:
  - jekyll-archives

encoding: utf-8
permalink: "/:categories/:title/"

# Build settings
markdown: kramdown

# Generated image settings
image:
  source: uploads
  output: generated
  presets:
    thumb:
      width: 300
      height: 300

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Archive pages
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: 'cat-archive'
  permalinks:
    category: '/:name/'

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'