# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

gems:
  - jekyll-archives

encoding: utf-8
permalink: "/:categories/:title/"

# Build settings
markdown: kramdown

# Generated image settings
image:
  source: uploads
  output: generated
  presets:
    thumb:
      width: 300
      height: 300

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Archive pages
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: 'cat-archive'
  permalinks:
    category: '/:name/'

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'